# generated by datamodel-codegen:
#   filename:  _combined.json
#   timestamp: 2026-03-06T22:45:09+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


class Model(RootModel[Any]):
    root: Any


class BboxSelection(BaseModel):
    bbox_norm: list[float] = Field(..., max_length=4, min_length=4)
    page: conint(ge=0)


class ChatRequest(BaseModel):
    doc_id: str
    message: str
    model: str | None = None
    provider: str | None = None
    selections: list[BboxSelection] | None = None


class Kind(StrEnum):
    TextDelta = 'TextDelta'


class ChatStreamEvent1(BaseModel):
    kind: Kind
    text: str


class Kind1(StrEnum):
    ToolCallStart = 'ToolCallStart'


class ChatStreamEvent2(BaseModel):
    kind: Kind1
    name: str


class Kind2(StrEnum):
    ToolCallDelta = 'ToolCallDelta'


class ChatStreamEvent3(BaseModel):
    kind: Kind2
    text: str


class Kind3(StrEnum):
    ToolCallDone = 'ToolCallDone'


class ChatStreamEvent4(BaseModel):
    arguments: Any
    id: str
    kind: Kind3
    name: str


class Kind4(StrEnum):
    MessageDone = 'MessageDone'


class ChatStreamEvent5(BaseModel):
    content: str | None = None
    kind: Kind4
    role: str
    tool_calls: Any | None = None


class Kind5(StrEnum):
    CitationData = 'CitationData'


class Kind6(StrEnum):
    AgentDone = 'AgentDone'


class ChatStreamEvent7(BaseModel):
    kind: Kind6


class Kind7(StrEnum):
    Error = 'Error'


class ChatStreamEvent8(BaseModel):
    kind: Kind7
    message: str


class EvidenceItem(BaseModel):
    bbox_norm: list[float] = Field(..., max_length=4, min_length=4)
    page: conint(ge=0)
    score: float
    span_id: str
    text: str


class IngestResponse(BaseModel):
    doc_id: str
    ingest: Any
    n_pages: conint(ge=0)
    n_spans: conint(ge=0)


class VectorizeResponse(BaseModel):
    dim: conint(ge=0) | None = None
    doc_id: str
    model: str
    n_embedded: conint(ge=0)
    n_skipped: conint(ge=0) | None = None
    was_cached: bool


class ChatStreamEvent6(BaseModel):
    items: list[EvidenceItem]
    kind: Kind5
    tool_call_id: str
    tool_name: str


class ChatStreamEvent(
    RootModel[
        ChatStreamEvent1
        | ChatStreamEvent2
        | ChatStreamEvent3
        | ChatStreamEvent4
        | ChatStreamEvent5
        | ChatStreamEvent6
        | ChatStreamEvent7
        | ChatStreamEvent8
    ]
):
    root: (
        ChatStreamEvent1
        | ChatStreamEvent2
        | ChatStreamEvent3
        | ChatStreamEvent4
        | ChatStreamEvent5
        | ChatStreamEvent6
        | ChatStreamEvent7
        | ChatStreamEvent8
    ) = Field(..., title='ChatStreamEvent')
